### PR TITLE
Fix empty links

### PR DESCRIPTION
**Pull request by jfranciscosousa**
Changes the target of turbo frames so the page navigation is applied to the whole page instead of the single frame.

It also fixes all the instances of "books of X user" links, to use the new route.

### CODE REVIEW

**Comment by jpcorreia99** [comment]
Could you please remember me in what areas of the website are these components used?

Also, could you fix on this PR that bug regarding the user filter not working correctly or do you think it's more approriate on a separate PR?

**Comment by jfranciscosousa** [comment]
@jpcorreia99 they are used to render the content of the gathering on the home page and to render all the books in one gathering. They are async pages that are loaded on demand to avoid loading everything at once, which was making the whole app pretty unusable lately as we were adding books and gatherings.

The issue you speak off is resolved I believe.

**Comment by jfranciscosousa** [comment]
@jpcorreia99 oh I get what you say. We were using the wrong link, it should be `user_books_path` now.

**Comment by jfranciscosousa** [comment]
But essentially by using this new thing from `hotwired`, each gathering in the books list is a network request, and they are made in order, top to bottom, so the page loads nearly instantly and users can see stuff immediately. You can see the network tab on the dev tools to check what is happening.

And no, I won't add pagination / infinite scroll atm, that takes too much work and this works fine for people now.

**Comment by jpcorreia99** [comment]
Thanks for the explanation and the improvements.

Regarding what I meant about the filtering by users, the problem is still there. Don't know if you have some commit which has not been pushed tho.

You can replicate this by first going to the /books endpoint and then, on the frame of a book, clicking on one of the persons which presented it. Instead of showing all the books that person presented, a blank page is rendered.

image
image

**Comment by jfranciscosousa** [comment]
Lol yes, did not push. Should be available in 10 minutes.

**Review by jpcorreia99 — APPROVED** [review]

**Pull request merged**
