### PR TITLE
Popup fixes and mobile fixes

### PR DESCRIPTION
**Pull request by jfranciscosousa**
Some mobile improvements on the Popup and Presentation areas.

Also makes the review apps have a moderator user, for testing.

Examples:
image

image

### CODE REVIEW

**Comment by jpcorreia99** [comment]
Things seem to be a bit broken on my side: 
 - no space between Next bookclub session and the date
 - gathering are automatically already open and can't be closed
image

**Comment by jpcorreia99** [comment]
Also, shouldn't the popup not occupy all the screen and have a scrollbar?

image

**Comment by jpcorreia99** [comment]
The popups also seem no not be rendering correctly sometimes in the /book page (Don't worry about the zoom, I zoomed out to show the whole page)

image

**Comment by jpcorreia99** [comment]
This also happens on the mobile view (I'm using Firefox btw)

image

**Comment by jfranciscosousa** [comment]
Weird, I'll debug with firefox then

**Comment by jfranciscosousa** [comment]
Things are not broken on my side and I'll add data to Heroku to show that they are working correctly elsewhere. The most likely scenario is a problem on your end, missing `yarn install`, `bundle install`, or a broken Node.

**Comment by jpcorreia99** [comment]
Okay, I ran the commands and all is woking fine, there's just a very minute problem which is with the arrow not turning when a gathering is expanded/closed. But that's a ridicously small details and if it is incovenient to fix let it be.
image

Anyway I'll aprove the PR.

**Review by jpcorreia99 — APPROVED** [review]
Thank you for your contributions and for having the patience to tolerate some awful css. :shipit:

**Comment by jfranciscosousa** [comment]
I can put arrow spinning easily. But let me close this first.

**Comment by jfranciscosousa** [comment]
Fixed

**Pull request merged**
