### PR TITLE
Design improvements on the gathering creation page

### PR DESCRIPTION
**Pull request by jfranciscosousa**
image

Notable things:
- Use native date input
- Remove all CSS, use Tailwind
- Add an empty placeholder for the presentations, with Reader/Book labels.
- Increase spacings all around to feel more "calm"

Also includes fixes and touch-ups elsewhere, especially when dealing with removing CSS.

Also adds CSS purge to remove unused Tailwind classes.

Look and feel of the native date on Brave (Chromium-based)

**It's native so no, we cannot change it or customize it to look whatever, and importing a date library just for this is not justifiable**

image

On Firefox 
image

The only major browser without this is Safari, and probably some mobile devices. But 90% of the world web users have it.

### CODE REVIEW

**Review by DavideSilva — APPROVED** [review]
Looking good! Fix the conflict and :shipit:

**Comment by jpcorreia99** [comment]
image
image
I think something may not be working for 100% of the screens

**Comment by jfranciscosousa** [comment]
Conflict resolution on my side broken literally everything. Fixed

**Comment by jpcorreia99** [comment]
I'm a bit busy right now but as soon as I'm free I'll take a look at it, I'll make it a urgency on my side. Thank you for all your contributions

**Comment by jfranciscosousa** [comment]
Fixed 
image

**Comment by jfranciscosousa** [comment]
Sorry @jpcorreia99 I'm going to merge this because it's kinda blocking me. But if you find anything leave an issue and I'll get to that.

**Comment by jpcorreia99** [comment]
No worries, I was studying for a test but gave it a quick look and all seemed fine

**Pull request merged**
